IMAGE_NAME = "centos/8"
API_SERVER_IP = "192.168.13.37"
CLUSTER_NAME = "enron.corp.uat.local"
VM_MEMORY = "2048"
DNS_SERVER = "1.1.1.1" 

Vagrant.configure("2") do |config|
    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: API_SERVER_IP
        master.vm.hostname = "#{CLUSTER_NAME}-k8s-control-plane"
        master.ssh.insert_key = false
        master.vm.boot_timeout = 800
        master.ssh.private_key_path = ["C:/Users/meen/.vagrant.d/vagrant-id_rsa", "C:/Users/meen/.vagrant.d/insecure_private_key"]
        master.vm.provision "file", source: "C:/Users/meen/.vagrant.d/vagrant-id_rsa.pub", destination: "~/.ssh/authorized_keys"
        master.vm.provider :virtualbox do |vb|
            vb.name = "#{CLUSTER_NAME}-k8s-control-plane"
            vb.memory = VM_MEMORY
            vb.cpus = 2 #tweak cpu and memory later
        end
        master.vm.provision "common", type: "shell", path: "init/common.sh"
    end
end