Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"
  # config.ssh.insert_key = false
  # config.vm.boot_timeout = 800
  # config.ssh.private_key_path = ["C:/Users/meen/.vagrant.d/vagrant-id_rsa", "C:/Users/meen/.vagrant.d/insecure_private_key"]
  # config.vm.provision "file", source: "C:/Users/meen/.vagrant.d/vagrant-id_rsa.pub", destination: "~/.ssh/authorized_keys"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y 
  SHELL
end